language: node_js
node_js:
  - "4"
  - "5"
  - "node"
services:
  - docker
before_install:
  - cd registration-web
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g npm@^3
script:
  - npm test
  - npm run build:docker
sudo: required
